/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_eoe_showimg_Bridge */

#ifndef _Included_cn_eoe_showimg_Bridge
#define _Included_cn_eoe_showimg_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: onBridgeInitListener */
/*
 * Class:     cn_eoe_showimg_Bridge
 * Method:    showImg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_eoe_showimg_Bridge_showImg
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_eoe_showimg_Bridge
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_eoe_showimg_Bridge_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
