/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_eoe_conncc_CCBridge */

#ifndef _Included_cn_eoe_conncc_CCBridge
#define _Included_cn_eoe_conncc_CCBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_eoe_conncc_CCBridge
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_eoe_conncc_CCBridge_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
